name: age-cli
version: 'v1.0+git'
summary: age is a simple, modern and secure file encryption tool.
description: |
    age is a simple, modern and secure file encryption tool, format, and Go library. 
    It features small explicit keys, no config options, and UNIX-style composability. 
    age was designed by [@Benjojo12](https://twitter.com/Benjojo12) and [@FiloSottile](https://twitter.com/FiloSottile). For the full documentation, read [the age(1) man page](https://filippo.io/age/age.1).
compression: lzo
confinement: strict
base: core20
parts:
  age-build:
    plugin: make
    build-snaps: [go]
    source: .
    build-packages: [gcc, make]
    stage-packages: [gcc, make]
    make-parameters: []
layout:
  /usr/bin/age-cli:
    symlink: $SNAP_DATA/usr/bin/age-cli
  /usr/bin/age-keygen-cli:
    symlink: $SNAP_DATA/usr/bin/age-keygen-cli
apps:
  age-cli:
    command: age-cli
  age-keygen-cli:
    command: age-keygen-cli
